version: '3'
services:
  mongodb:
    image: mongo:6.0-focal   # Use the latest MongoDB LTS image
    container_name: mongodb
    ports:
      - "27017:27017"     # Map container port 27017 to host port 27017
    volumes:
      - mongodb_data:/data/db
    restart: always

volumes:
  mongodb_data:
